// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5MWbwJWqVTOxHMuXN62GI719CE5f0C3U',
    appId: '1:242639271813:web:8906f09b6f7b69b3f2b6ec',
    messagingSenderId: '242639271813',
    projectId: 'easynutrition-17c05',
    authDomain: 'easynutrition-17c05.firebaseapp.com',
    databaseURL: 'https://easynutrition-17c05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easynutrition-17c05.appspot.com',
    measurementId: 'G-1CDJ97GZLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ2MvfxtzatJudZNb5NLc6792o-kVdo5I',
    appId: '1:242639271813:android:ee45dd87bce6f2faf2b6ec',
    messagingSenderId: '242639271813',
    projectId: 'easynutrition-17c05',
    databaseURL: 'https://easynutrition-17c05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easynutrition-17c05.appspot.com',
  );
}
